### ISSUE TITLE
Updated TODO must be saved to repo

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/Deadliner-2-Bot#14]
https://github.com/Garuda-1/Deadliner-2-Bot/blob/11b21802e544132c1502faf28387077e630a2c89/src/main/java/ru/itmo/sd/deadliner2bot/state/AddStartDateState.java#L67

**Comment by Garuda-1** [comment]
Will be fixed in https://tracker.yandex.ru/DEV-22

**Comment by Garuda-1** [comment]
Fixed now, you can pull changes from the `dev` branch.
